/**
 * Seed script using real data from UT Housing scraper
 * Uses the scraped-apartments.json file generated by scrape-listings.ts
 */

import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { Pool } from "pg";
import * as fs from "fs";
import * as path from "path";

// Interface matching our scraper output
interface ScrapedApartment {
  id: number;
  name: string;
  slug: string;
  address: string;
  city: string;
  state: string;
  zipCode: string;
  latitude: number;
  longitude: number;
  priceMin: number | null;
  priceMax: number | null;
  pricePerPerson: boolean;
  bedroomMin: number;
  bedroomMax: number;
  bathroomMin: number;
  bathroomMax: number;
  phone: string | null;
  email: string | null;
  website: string | null;
  walkTime: number | null;
  imageUrl: string | null;
  images: string[];
  neighborhood: string;
  category: string;
  description: string | null;
  amenities: string[];
  unitFeatures: string[];
  propertyFeatures: string[];
  utilities: string[];
  floorplans: Array<{
    bedrooms: number;
    bathrooms: number;
    rentMin: number;
    rentMax: number;
    sqft: number | null;
  }>;
  petsAllowed: boolean;
  furnished: boolean;
  hasParking: boolean;
  hasPool: boolean;
  hasGym: boolean;
  hasLaundry: boolean;
  detailUrl: string;
}

// Initialize Prisma
const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
});
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

// Strip HTML tags from description
function stripHtml(html: string | null): string | null {
  if (!html) return null;
  return html
    .replace(/<[^>]*>/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 2000);
}

// Map feature strings to amenity names
function mapFeatureToAmenity(feature: string): string | null {
  const featureLower = feature.toLowerCase();

  // Building amenities
  if (featureLower.includes("pool") || featureLower.includes("swim"))
    return "Pool";
  if (featureLower.includes("fitness") || featureLower.includes("gym"))
    return "Fitness Center";
  if (
    featureLower.includes("study") ||
    featureLower.includes("business center")
  )
    return "Study Rooms";
  if (featureLower.includes("game room")) return "Game Room";
  if (featureLower.includes("theater") || featureLower.includes("movie"))
    return "Theater Room";
  if (featureLower.includes("coffee") || featureLower.includes("cafe"))
    return "Coffee Bar";
  if (featureLower.includes("rooftop") && !featureLower.includes("pool"))
    return "Rooftop Deck";
  if (featureLower.includes("courtyard") || featureLower.includes("outdoor"))
    return "Courtyard";
  if (featureLower.includes("bbq") || featureLower.includes("grill"))
    return "BBQ/Grill Area";
  if (featureLower.includes("dog") || featureLower.includes("pet park"))
    return "Dog Park";
  if (featureLower.includes("bike")) return "Bike Storage";
  if (featureLower.includes("package") || featureLower.includes("parcel"))
    return "Package Lockers";
  if (featureLower.includes("parking") || featureLower.includes("garage"))
    return "Parking Garage";
  if (featureLower.includes("ev ") || featureLower.includes("electric vehicle"))
    return "EV Charging";
  if (featureLower.includes("security") || featureLower.includes("patrol"))
    return "24/7 Security";
  if (
    featureLower.includes("controlled access") ||
    featureLower.includes("gated")
  )
    return "Controlled Access";
  if (featureLower.includes("elevator")) return "Elevator";

  // Unit amenities
  if (featureLower.includes("washer") && featureLower.includes("dryer"))
    return "In-Unit Washer/Dryer";
  if (featureLower.includes("dishwasher")) return "Dishwasher";
  if (featureLower.includes("stainless")) return "Stainless Appliances";
  if (featureLower.includes("hardwood") || featureLower.includes("wood floor"))
    return "Hardwood Floors";
  if (
    featureLower.includes("walk-in closet") ||
    featureLower.includes("walkin closet")
  )
    return "Walk-In Closet";
  if (
    featureLower.includes("balcony") ||
    featureLower.includes("patio") ||
    featureLower.includes("terrace")
  )
    return "Balcony/Patio";
  if (featureLower.includes("furnished")) return "Furnished Available";
  if (featureLower.includes("smart") && featureLower.includes("therm"))
    return "Smart Thermostat";
  if (featureLower.includes("smart") && featureLower.includes("lock"))
    return "Smart Locks";
  if (featureLower.includes("granite")) return "Granite Countertops";
  if (featureLower.includes("ceiling") && featureLower.includes("9"))
    return "High Ceilings";

  // Utilities
  if (featureLower.includes("internet") || featureLower.includes("wifi"))
    return "High-Speed Internet";
  if (featureLower.includes("cable")) return "Cable Included";
  if (featureLower.includes("water") && featureLower.includes("includ"))
    return "Water Included";
  if (featureLower.includes("electric") && featureLower.includes("includ"))
    return "Electric Included";

  return null;
}

async function main() {
  console.log("🌱 Starting seed with real UT Housing data...\n");

  // Load scraped data
  const scrapedPath = path.join(
    __dirname,
    "../scripts/scraped-apartments.json",
  );
  if (!fs.existsSync(scrapedPath)) {
    console.error(
      "❌ scraped-apartments.json not found! Run 'npm run scrape' first.",
    );
    process.exit(1);
  }

  const apartments: ScrapedApartment[] = JSON.parse(
    fs.readFileSync(scrapedPath, "utf-8"),
  );
  console.log(`📂 Loaded ${apartments.length} apartments from scraped data\n`);

  // Clear existing data
  console.log("🗑️  Clearing existing data...");
  await prisma.apartmentImage.deleteMany();
  await prisma.apartmentAmenity.deleteMany();
  await prisma.floorPlan.deleteMany();
  await prisma.apartment.deleteMany();
  await prisma.amenity.deleteMany();
  await prisma.neighborhood.deleteMany();

  // Create neighborhoods
  console.log("\n🏘️  Creating neighborhoods...");
  const neighborhoodData = [
    {
      name: "West Campus",
      slug: "west-campus",
      description:
        "The heart of student life, located just west of UT campus. Known for high-rise apartments, vibrant nightlife, and walkability to campus.",
    },
    {
      name: "North Campus",
      slug: "north-campus",
      description:
        "A quieter residential area north of the main campus, popular with graduate students seeking a calmer environment.",
    },
    {
      name: "Hyde Park",
      slug: "hyde-park",
      description:
        "A historic neighborhood with charming older homes, tree-lined streets, and a strong sense of community.",
    },
    {
      name: "Riverside",
      slug: "riverside",
      description:
        "An affordable area south of Lady Bird Lake with good transit connections to campus.",
    },
    {
      name: "Far Campus",
      slug: "far-campus",
      description:
        "Areas further from UT campus, offering more space and lower rents with longer commute times.",
    },
    {
      name: "East Campus",
      slug: "east-campus",
      description:
        "The emerging east side with growing restaurant and entertainment options.",
    },
    {
      name: "Other",
      slug: "other",
      description:
        "Other Austin neighborhoods with off-campus housing options.",
    },
  ];

  const neighborhoods: Record<
    string,
    { id: string; name: string; slug: string }
  > = {};
  for (const data of neighborhoodData) {
    const neighborhood = await prisma.neighborhood.create({ data });
    neighborhoods[data.name] = neighborhood;
    console.log(`   ✓ ${data.name}`);
  }

  // Create amenities
  console.log("\n🎯 Creating amenities...");
  const amenityData = [
    // Building amenities
    { name: "Pool", category: "Building", icon: "waves" },
    { name: "Rooftop Pool", category: "Building", icon: "waves" },
    { name: "Fitness Center", category: "Building", icon: "dumbbell" },
    { name: "Study Rooms", category: "Building", icon: "book-open" },
    { name: "Business Center", category: "Building", icon: "briefcase" },
    { name: "Clubhouse", category: "Building", icon: "home" },
    { name: "Game Room", category: "Building", icon: "gamepad-2" },
    { name: "Theater Room", category: "Building", icon: "film" },
    { name: "Coffee Bar", category: "Building", icon: "coffee" },
    { name: "Rooftop Deck", category: "Building", icon: "sun" },
    { name: "Courtyard", category: "Building", icon: "trees" },
    { name: "BBQ/Grill Area", category: "Building", icon: "flame" },
    { name: "Dog Park", category: "Building", icon: "dog" },
    { name: "Bike Storage", category: "Building", icon: "bike" },
    { name: "Package Lockers", category: "Building", icon: "package" },
    { name: "Parking Garage", category: "Building", icon: "car" },
    { name: "EV Charging", category: "Building", icon: "zap" },
    { name: "24/7 Security", category: "Building", icon: "shield" },
    { name: "Controlled Access", category: "Building", icon: "key" },
    { name: "Elevator", category: "Building", icon: "arrow-up" },
    // Unit amenities
    { name: "In-Unit Washer/Dryer", category: "Unit", icon: "shirt" },
    { name: "Dishwasher", category: "Unit", icon: "utensils" },
    { name: "Stainless Appliances", category: "Unit", icon: "refrigerator" },
    { name: "Hardwood Floors", category: "Unit", icon: "layers" },
    { name: "Walk-In Closet", category: "Unit", icon: "door-open" },
    { name: "Balcony/Patio", category: "Unit", icon: "sun" },
    { name: "Furnished Available", category: "Unit", icon: "sofa" },
    { name: "Smart Thermostat", category: "Unit", icon: "thermometer" },
    { name: "Smart Locks", category: "Unit", icon: "lock" },
    { name: "Granite Countertops", category: "Unit", icon: "square" },
    { name: "High Ceilings", category: "Unit", icon: "arrow-up" },
    // Utilities
    { name: "High-Speed Internet", category: "Utilities", icon: "wifi" },
    { name: "Cable Included", category: "Utilities", icon: "tv" },
    { name: "Water Included", category: "Utilities", icon: "droplet" },
    { name: "Electric Included", category: "Utilities", icon: "zap" },
    // Pets
    { name: "Pets Allowed", category: "Pets", icon: "paw-print" },
  ];

  const amenities: Record<string, { id: string; name: string }> = {};
  for (const data of amenityData) {
    const amenity = await prisma.amenity.create({ data });
    amenities[data.name] = amenity;
  }
  console.log(`   ✓ Created ${Object.keys(amenities).length} amenities`);

  // Create apartments
  console.log("\n🏠 Creating apartments...");
  let created = 0;
  let skipped = 0;

  for (const apt of apartments) {
    try {
      // Get neighborhood
      const neighborhoodId =
        neighborhoods[apt.neighborhood]?.id || neighborhoods["Other"].id;

      // Generate unique slug
      const baseSlug =
        apt.slug || apt.name.toLowerCase().replace(/[^a-z0-9]+/g, "-");
      const uniqueSlug = `${baseSlug}-${apt.id}`;

      // Determine parking type
      let parkingType: string | null = null;
      if (apt.hasParking) {
        parkingType = "Garage";
      }

      // Create the apartment (matching actual Prisma schema)
      const apartment = await prisma.apartment.create({
        data: {
          name: apt.name,
          slug: uniqueSlug,
          address: apt.address,
          city: apt.city,
          state: apt.state,
          zipCode: apt.zipCode,
          latitude: apt.latitude,
          longitude: apt.longitude,
          neighborhoodId,
          phone: apt.phone,
          email: apt.email,
          website: apt.website || apt.detailUrl,
          walkTime: apt.walkTime,
          bikeTime: apt.walkTime ? Math.round(apt.walkTime / 3) : null,
          busTime: apt.walkTime ? Math.round(apt.walkTime / 2) : null,
          petFriendly: apt.petsAllowed,
          parkingType,
          description: stripHtml(apt.description),
          imageUrl: apt.images[0] || null,
          featured: false,
          available: true,
        },
      });

      // Add images
      if (apt.images.length > 0) {
        for (let i = 0; i < Math.min(apt.images.length, 10); i++) {
          await prisma.apartmentImage.create({
            data: {
              apartmentId: apartment.id,
              url: apt.images[i],
              caption: `${apt.name} image ${i + 1}`,
              isPrimary: i === 0,
            },
          });
        }
      }

      // Add floor plans from scraper data
      if (apt.floorplans.length > 0) {
        for (const fp of apt.floorplans) {
          if (fp.rentMin > 0) {
            await prisma.floorPlan.create({
              data: {
                apartmentId: apartment.id,
                name: `${fp.bedrooms}BR/${fp.bathrooms}BA`,
                bedrooms: fp.bedrooms,
                bathrooms: fp.bathrooms,
                sqft: fp.sqft,
                priceMin: fp.rentMin,
                priceMax: fp.rentMax || fp.rentMin,
                pricePerPerson: apt.pricePerPerson,
                availableNow: true,
              },
            });
          }
        }
      } else {
        // Create a default floor plan from the apartment's overall pricing
        await prisma.floorPlan.create({
          data: {
            apartmentId: apartment.id,
            name:
              apt.bedroomMin === apt.bedroomMax
                ? `${apt.bedroomMin}BR/${apt.bathroomMin}BA`
                : `${apt.bedroomMin}-${apt.bedroomMax}BR`,
            bedrooms: apt.bedroomMin,
            bathrooms: apt.bathroomMin,
            sqft: null,
            priceMin: apt.priceMin || 0,
            priceMax: apt.priceMax || apt.priceMin || 0,
            pricePerPerson: apt.pricePerPerson,
            availableNow: true,
          },
        });
      }

      // Map and add amenities
      const mappedAmenityNames = new Set<string>();

      // Map from features arrays
      const allFeatures = [
        ...apt.amenities,
        ...apt.unitFeatures,
        ...apt.propertyFeatures,
      ];
      for (const feature of allFeatures) {
        const amenityName = mapFeatureToAmenity(feature);
        if (amenityName && amenities[amenityName]) {
          mappedAmenityNames.add(amenityName);
        }
      }

      // Add based on boolean flags
      if (apt.petsAllowed && amenities["Pets Allowed"]) {
        mappedAmenityNames.add("Pets Allowed");
      }
      if (apt.hasPool && amenities["Pool"]) {
        mappedAmenityNames.add("Pool");
      }
      if (apt.hasGym && amenities["Fitness Center"]) {
        mappedAmenityNames.add("Fitness Center");
      }
      if (apt.hasLaundry && amenities["In-Unit Washer/Dryer"]) {
        mappedAmenityNames.add("In-Unit Washer/Dryer");
      }
      if (apt.hasParking && amenities["Parking Garage"]) {
        mappedAmenityNames.add("Parking Garage");
      }
      if (apt.furnished && amenities["Furnished Available"]) {
        mappedAmenityNames.add("Furnished Available");
      }

      // Create amenity connections
      for (const amenityName of mappedAmenityNames) {
        await prisma.apartmentAmenity.create({
          data: {
            apartmentId: apartment.id,
            amenityId: amenities[amenityName].id,
          },
        });
      }

      created++;
      console.log(`   ✓ ${apt.name} (${apt.neighborhood})`);
    } catch (error) {
      skipped++;
      console.error(
        `   ✗ Failed to create ${apt.name}:`,
        (error as Error).message,
      );
    }
  }

  console.log(`\n✅ Seed completed successfully!`);
  console.log(`   - ${Object.keys(neighborhoods).length} neighborhoods`);
  console.log(`   - ${Object.keys(amenities).length} amenities`);
  console.log(`   - ${created} apartments created`);
  if (skipped > 0) {
    console.log(`   - ${skipped} apartments skipped due to errors`);
  }

  await prisma.$disconnect();
  await pool.end();
}

main().catch((e) => {
  console.error("Seed failed:", e);
  process.exit(1);
});
