/**
 * Incremental sync script using real data from UT Housing scraper.
 * Uses scraped-apartments.json generated by scrape-listings.ts.
 *
 * Key design decisions:
 *  - Upserts apartments by sourceId instead of delete-all + re-create
 *  - Preserves user data (favorites, price snapshots) across re-seeds
 *  - Marks apartments not in the current scrape as unavailable
 *  - Reference data (neighborhoods, amenities) is upserted, never deleted
 */

import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { Pool } from "pg";
import * as fs from "fs";
import * as path from "path";
import type { ScrapedApartment } from "../src/types/scraped";

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

function stripHtml(html: string | null): string | null {
  if (!html) return null;
  return html
    .replace(/<[^>]*>/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 2000);
}

function mapFeatureToAmenity(feature: string): string | null {
  const f = feature.toLowerCase();

  if (f.includes("pool") || f.includes("swim")) return "Pool";
  if (f.includes("fitness") || f.includes("gym")) return "Fitness Center";
  if (f.includes("study") || f.includes("business center")) return "Study Rooms";
  if (f.includes("game room")) return "Game Room";
  if (f.includes("theater") || f.includes("movie")) return "Theater Room";
  if (f.includes("coffee") || f.includes("cafe")) return "Coffee Bar";
  if (f.includes("rooftop") && !f.includes("pool")) return "Rooftop Deck";
  if (f.includes("courtyard") || f.includes("outdoor")) return "Courtyard";
  if (f.includes("bbq") || f.includes("grill")) return "BBQ/Grill Area";
  if (f.includes("dog") || f.includes("pet park")) return "Dog Park";
  if (f.includes("bike")) return "Bike Storage";
  if (f.includes("package") || f.includes("parcel")) return "Package Lockers";
  if (f.includes("parking") || f.includes("garage")) return "Parking Garage";
  if (f.includes("ev ") || f.includes("electric vehicle")) return "EV Charging";
  if (f.includes("security") || f.includes("patrol")) return "24/7 Security";
  if (f.includes("controlled access") || f.includes("gated")) return "Controlled Access";
  if (f.includes("elevator")) return "Elevator";
  if (f.includes("washer") && f.includes("dryer")) return "In-Unit Washer/Dryer";
  if (f.includes("dishwasher")) return "Dishwasher";
  if (f.includes("stainless")) return "Stainless Appliances";
  if (f.includes("hardwood") || f.includes("wood floor")) return "Hardwood Floors";
  if (f.includes("walk-in closet") || f.includes("walkin closet")) return "Walk-In Closet";
  if (f.includes("balcony") || f.includes("patio") || f.includes("terrace")) return "Balcony/Patio";
  if (f.includes("furnished")) return "Furnished Available";
  if (f.includes("smart") && f.includes("therm")) return "Smart Thermostat";
  if (f.includes("smart") && f.includes("lock")) return "Smart Locks";
  if (f.includes("granite")) return "Granite Countertops";
  if (f.includes("ceiling") && f.includes("9")) return "High Ceilings";
  if (f.includes("internet") || f.includes("wifi")) return "High-Speed Internet";
  if (f.includes("cable")) return "Cable Included";
  if (f.includes("water") && f.includes("includ")) return "Water Included";
  if (f.includes("electric") && f.includes("includ")) return "Electric Included";

  return null;
}

const NEIGHBORHOOD_DATA = [
  { name: "West Campus", slug: "west-campus", description: "The heart of student life, located just west of UT campus. Known for high-rise apartments, vibrant nightlife, and walkability to campus." },
  { name: "North Campus", slug: "north-campus", description: "A quieter residential area north of the main campus, popular with graduate students seeking a calmer environment." },
  { name: "Hyde Park", slug: "hyde-park", description: "A historic neighborhood with charming older homes, tree-lined streets, and a strong sense of community." },
  { name: "Riverside", slug: "riverside", description: "An affordable area south of Lady Bird Lake with good transit connections to campus." },
  { name: "Far Campus", slug: "far-campus", description: "Areas further from UT campus, offering more space and lower rents with longer commute times." },
  { name: "East Campus", slug: "east-campus", description: "The emerging east side with growing restaurant and entertainment options." },
  { name: "Other", slug: "other", description: "Other Austin neighborhoods with off-campus housing options." },
];

const AMENITY_DATA = [
  { name: "Pool", category: "Building", icon: "waves" },
  { name: "Rooftop Pool", category: "Building", icon: "waves" },
  { name: "Fitness Center", category: "Building", icon: "dumbbell" },
  { name: "Study Rooms", category: "Building", icon: "book-open" },
  { name: "Business Center", category: "Building", icon: "briefcase" },
  { name: "Clubhouse", category: "Building", icon: "home" },
  { name: "Game Room", category: "Building", icon: "gamepad-2" },
  { name: "Theater Room", category: "Building", icon: "film" },
  { name: "Coffee Bar", category: "Building", icon: "coffee" },
  { name: "Rooftop Deck", category: "Building", icon: "sun" },
  { name: "Courtyard", category: "Building", icon: "trees" },
  { name: "BBQ/Grill Area", category: "Building", icon: "flame" },
  { name: "Dog Park", category: "Building", icon: "dog" },
  { name: "Bike Storage", category: "Building", icon: "bike" },
  { name: "Package Lockers", category: "Building", icon: "package" },
  { name: "Parking Garage", category: "Building", icon: "car" },
  { name: "EV Charging", category: "Building", icon: "zap" },
  { name: "24/7 Security", category: "Building", icon: "shield" },
  { name: "Controlled Access", category: "Building", icon: "key" },
  { name: "Elevator", category: "Building", icon: "arrow-up" },
  { name: "In-Unit Washer/Dryer", category: "Unit", icon: "shirt" },
  { name: "Dishwasher", category: "Unit", icon: "utensils" },
  { name: "Stainless Appliances", category: "Unit", icon: "refrigerator" },
  { name: "Hardwood Floors", category: "Unit", icon: "layers" },
  { name: "Walk-In Closet", category: "Unit", icon: "door-open" },
  { name: "Balcony/Patio", category: "Unit", icon: "sun" },
  { name: "Furnished Available", category: "Unit", icon: "sofa" },
  { name: "Smart Thermostat", category: "Unit", icon: "thermometer" },
  { name: "Smart Locks", category: "Unit", icon: "lock" },
  { name: "Granite Countertops", category: "Unit", icon: "square" },
  { name: "High Ceilings", category: "Unit", icon: "arrow-up" },
  { name: "High-Speed Internet", category: "Utilities", icon: "wifi" },
  { name: "Cable Included", category: "Utilities", icon: "tv" },
  { name: "Water Included", category: "Utilities", icon: "droplet" },
  { name: "Electric Included", category: "Utilities", icon: "zap" },
  { name: "Pets Allowed", category: "Pets", icon: "paw-print" },
];

function computeMinMaxPrice(apt: ScrapedApartment): { minPrice: number | null; maxPrice: number | null } {
  if (apt.floorplans.length > 0) {
    const rents = apt.floorplans.map((fp) => fp.rentMin).filter((r) => r > 0);
    const maxRents = apt.floorplans.map((fp) => fp.rentMax || fp.rentMin).filter((r) => r > 0);
    return {
      minPrice: rents.length > 0 ? Math.min(...rents) : apt.priceMin,
      maxPrice: maxRents.length > 0 ? Math.max(...maxRents) : apt.priceMax,
    };
  }
  return { minPrice: apt.priceMin, maxPrice: apt.priceMax };
}

async function main() {
  console.log("Starting incremental sync with UT Housing data...\n");

  const scrapedPath = path.join(__dirname, "../scripts/scraped-apartments.json");
  if (!fs.existsSync(scrapedPath)) {
    console.error("scraped-apartments.json not found! Run 'npm run scrape' first.");
    process.exit(1);
  }

  const apartments: ScrapedApartment[] = JSON.parse(
    fs.readFileSync(scrapedPath, "utf-8"),
  );
  console.log(`Loaded ${apartments.length} apartments from scraped data\n`);

  // Phase 1 — Upsert reference data
  console.log("Upserting neighborhoods...");
  const neighborhoods: Record<string, string> = {};
  for (const n of NEIGHBORHOOD_DATA) {
    const record = await prisma.neighborhood.upsert({
      where: { slug: n.slug },
      update: { name: n.name, description: n.description },
      create: n,
    });
    neighborhoods[n.name] = record.id;
    console.log(`  + ${n.name}`);
  }

  console.log("\nUpserting amenities...");
  const amenityMap: Record<string, string> = {};
  for (const a of AMENITY_DATA) {
    const record = await prisma.amenity.upsert({
      where: { name: a.name },
      update: { category: a.category, icon: a.icon },
      create: a,
    });
    amenityMap[a.name] = record.id;
  }
  console.log(`  + ${Object.keys(amenityMap).length} amenities`);

  // Phase 2 — Upsert apartments
  console.log("\nSyncing apartments...");

  const seenSourceIds = new Set<number>();
  let created = 0;
  let updated = 0;
  let skipped = 0;

  for (const apt of apartments) {
    try {
      seenSourceIds.add(apt.id);
      const neighborhoodId = neighborhoods[apt.neighborhood] || neighborhoods["Other"];
      const baseSlug = apt.slug || apt.name.toLowerCase().replace(/[^a-z0-9]+/g, "-");
      const uniqueSlug = `${baseSlug}-${apt.id}`;
      const { minPrice, maxPrice } = computeMinMaxPrice(apt);

      const apartmentData = {
        name: apt.name,
        slug: uniqueSlug,
        address: apt.address,
        city: apt.city,
        state: apt.state,
        zipCode: apt.zipCode,
        latitude: apt.latitude,
        longitude: apt.longitude,
        neighborhoodId,
        phone: apt.phone,
        email: apt.email,
        website: apt.website || apt.detailUrl,
        walkTime: apt.walkTime,
        petFriendly: apt.petsAllowed,
        parkingType: apt.hasParking ? "Garage" : null,
        description: stripHtml(apt.description),
        imageUrl: apt.images[0] || null,
        featured: false,
        available: true,
        sourceId: apt.id,
        minPrice: minPrice ?? 0,
        maxPrice: maxPrice ?? minPrice ?? 0,
      };

      // Find by sourceId first, then fall back to slug for apartments
      // that were seeded before the sourceId column was added.
      const existing =
        (await prisma.apartment.findUnique({ where: { sourceId: apt.id } })) ??
        (await prisma.apartment.findUnique({ where: { slug: uniqueSlug } }));

      let apartmentId: string;

      if (existing) {
        await prisma.apartment.update({
          where: { id: existing.id },
          data: apartmentData,
        });
        apartmentId = existing.id;
        updated++;
      } else {
        const record = await prisma.apartment.create({ data: apartmentData });
        apartmentId = record.id;
        created++;
      }

      // Rebuild images, floor plans, and amenity links for this apartment.
      // These are cheap reference data — rebuilding is simpler and safer than diffing.
      await prisma.apartmentImage.deleteMany({ where: { apartmentId } });
      await prisma.floorPlan.deleteMany({ where: { apartmentId } });
      await prisma.apartmentAmenity.deleteMany({ where: { apartmentId } });

      const images = apt.images.slice(0, 10).map((url, i) => ({
        apartmentId,
        url,
        caption: `${apt.name} image ${i + 1}`,
        isPrimary: i === 0,
        order: i,
      }));
      if (images.length > 0) {
        await prisma.apartmentImage.createMany({ data: images });
      }

      const floorPlans: {
        apartmentId: string; name: string; bedrooms: number; bathrooms: number;
        sqft: number | null; priceMin: number; priceMax: number;
        pricePerPerson: boolean; availableNow: boolean;
      }[] = [];

      if (apt.floorplans.length > 0) {
        for (const fp of apt.floorplans) {
          if (fp.rentMin <= 0) continue;
          floorPlans.push({
            apartmentId,
            name: `${fp.bedrooms}BR/${fp.bathrooms}BA`,
            bedrooms: fp.bedrooms,
            bathrooms: fp.bathrooms,
            sqft: fp.sqft,
            priceMin: fp.rentMin,
            priceMax: fp.rentMax || fp.rentMin,
            pricePerPerson: apt.pricePerPerson,
            availableNow: true,
          });
        }
      } else {
        floorPlans.push({
          apartmentId,
          name:
            apt.bedroomMin === apt.bedroomMax
              ? `${apt.bedroomMin}BR/${apt.bathroomMin}BA`
              : `${apt.bedroomMin}-${apt.bedroomMax}BR`,
          bedrooms: apt.bedroomMin,
          bathrooms: apt.bathroomMin,
          sqft: null,
          priceMin: apt.priceMin || 0,
          priceMax: apt.priceMax || apt.priceMin || 0,
          pricePerPerson: apt.pricePerPerson,
          availableNow: true,
        });
      }
      if (floorPlans.length > 0) {
        await prisma.floorPlan.createMany({ data: floorPlans });
      }

      const mappedNames = new Set<string>();
      const allFeatures = [...apt.amenities, ...apt.unitFeatures, ...apt.propertyFeatures];
      for (const feature of allFeatures) {
        const name = mapFeatureToAmenity(feature);
        if (name && amenityMap[name]) mappedNames.add(name);
      }
      if (apt.petsAllowed && amenityMap["Pets Allowed"]) mappedNames.add("Pets Allowed");
      if (apt.hasPool && amenityMap["Pool"]) mappedNames.add("Pool");
      if (apt.hasGym && amenityMap["Fitness Center"]) mappedNames.add("Fitness Center");
      if (apt.hasLaundry && amenityMap["In-Unit Washer/Dryer"]) mappedNames.add("In-Unit Washer/Dryer");
      if (apt.hasParking && amenityMap["Parking Garage"]) mappedNames.add("Parking Garage");
      if (apt.furnished && amenityMap["Furnished Available"]) mappedNames.add("Furnished Available");

      const amenityLinks = [...mappedNames].map((name) => ({
        apartmentId,
        amenityId: amenityMap[name],
      }));
      if (amenityLinks.length > 0) {
        await prisma.apartmentAmenity.createMany({ data: amenityLinks });
      }

      if ((created + updated) % 20 === 0) {
        console.log(`  ... ${created + updated} apartments processed`);
      }
    } catch (error) {
      skipped++;
      console.error(`  x Failed: ${apt.name}: ${(error as Error).message}`);
    }
  }

  // Phase 3 — Mark apartments not in the current scrape as unavailable
  console.log("\nMarking stale apartments as unavailable...");
  const staleResult = await prisma.apartment.updateMany({
    where: {
      sourceId: { not: null, notIn: [...seenSourceIds] },
      available: true,
    },
    data: { available: false },
  });
  if (staleResult.count > 0) {
    console.log(`  Marked ${staleResult.count} apartments as unavailable`);
  } else {
    console.log("  No stale apartments found");
  }

  console.log(`\nSync completed!`);
  console.log(`  - ${Object.keys(neighborhoods).length} neighborhoods`);
  console.log(`  - ${Object.keys(amenityMap).length} amenities`);
  console.log(`  - ${created} apartments created`);
  console.log(`  - ${updated} apartments updated`);
  if (skipped > 0) {
    console.log(`  - ${skipped} apartments skipped due to errors`);
  }

  await prisma.$disconnect();
  await pool.end();
}

main().catch((e) => {
  console.error("Sync failed:", e);
  process.exit(1);
});
